const teams=['Hyundai Unicorns','Samsung Lions','KT wiz','Yakult Swallows'];const rosters={
'Yakult Swallows':['xck018','VorZaves','owldoskq','kosame55','1Lov3_HW','woozlordd','1Lov3_Doy0un9','ANYWAY789','hamzziii','ggkkbt21','Akon_Kon','1Lov3_Darin','DANA_X1126','ShaltNK','dddfdsfc','Cola_1034657','willie06080','youdam2001','0X_Perfect','ghffhthhf','qwweush','tsnsjjssjjd','gorsky7'],
'KT wiz':['BaIemoon','Rozu_1x','Gre4n_Love','CUTI_STREET','jongpyokurai','terry0185','rayray24257978','kyota_kana','ncd1nos','KOREA_goodgubber','JerryEEENTNL','Sam0705_Sam0705','YutaNalDo','heerak2','sy_adi','ddnwwagefd9991','yu_x0412','sa1vationtrinity','kiabojiz','imgodkaito','H1n_Lx5h','Insanetricx','EIL1sback'],
'Hyundai Unicorns':['ho_0xz','wakashizz','nicemanman_1','xxsks_ekw','mandoo_19','klk122380','X_csm','ksmzsm123','Mylovesk62','apexghte','RxitoVII','Q_LDL','hwgahw76','graa_nice','Yoongichan0902','djhxjffj0','STINSONA','npm_apple','KRsungjae','JS13416','KimDoYoung_Good','Sam0705_Sam0705','kingkueen0s','OREO_5744','1ee_youngchan','needam0721','splint111','1Lov3_donghee'],
'Samsung Lions':['Ak1Kurai','NOOB_dghm','imnotswomi3','cool327000','kgimpepepspepe','AdenElec','FINX_Z7','TheYoungKing_N05','GAEQ_74HRUE','koreahom123467','sdy131221','dex1va1ly','crvhjc','EZEZEZoqo','Kevin707952','ezgame0303','demon_091033','Acthdfgvj','12twelve25','chosankru39','WgoodS1un_n1cegoodz','s9sdsei','kaname030844','aofo5934','tttttttrrrtttttttt','qqedcjdxcg','woojin_0503','10wjwdgha','dgshjgdj','SHJBMV']};
const $=id=>document.getElementById(id);const saved=JSON.parse(localStorage.getItem('kfbPlayerGameStats')||'[]');
function fillTeams(){teams.forEach(t=>{team.innerHTML+=`<option>${t}</option>`;opponent.innerHTML+=`<option>${t}</option>`});fillPlayers();team.value=teams[0];opponent.value=teams[1]}function fillPlayers(){player.innerHTML='';(rosters[team.value]||[]).forEach(p=>player.innerHTML+=`<option>${p}</option>`)}team.addEventListener('change',fillPlayers);
function render(){count.textContent=saved.length;records.innerHTML=saved.length?saved.map((r,i)=>`<div class="admin-record"><span>R${r.round}</span><b>${r.player}</b><small>${r.team} vs ${r.opponent} · ${r.h}/${r.ab} H/AB · ${r.hr} HR · ${r.rbi} RBI</small><button onclick="removeRecord(${i})">삭제</button></div>`).join(''):'<p class="admin-note">아직 입력된 기록이 없습니다.</p>'}window.removeRecord=i=>{saved.splice(i,1);persist();status.textContent='기록을 삭제했습니다.'};function persist(){localStorage.setItem('kfbPlayerGameStats',JSON.stringify(saved));render()}
$('add').onclick=()=>{const r={round:+$('round').value||0,team:team.value,opponent:opponent.value,player:player.value,pa:+$('pa').value||0,ab:+$('ab').value||0,h:+$('h').value||0,doubles:+$('doubles').value||0,triples:+$('triples').value||0,hr:+$('hr').value||0,rbi:+$('rbi').value||0,bb:+$('bb').value||0,so:+$('so').value||0};if(!r.round||r.team===r.opponent||!r.player){status.textContent='Round, 팀/상대팀, 선수를 확인하세요.';return}saved.push(r);persist();status.textContent=`${r.player}의 R${r.round} 기록을 저장했습니다.`};
$('clear').onclick=()=>{if(confirm('저장된 모든 기록을 삭제할까요?')){saved.length=0;persist();status.textContent='모든 기록을 삭제했습니다.'}};
$('export').onclick=()=>{const text=`const playerGameStats = ${JSON.stringify(saved,null,2)};`;const blob=new Blob([text],{type:'text/javascript;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='player-stats-data.js';a.click();URL.revokeObjectURL(a.href);status.textContent='player-stats-data.js를 만들었습니다. 이 파일 내용을 script.js의 playerGameStats에 반영하면 방문자에게 적용됩니다.'};fillTeams();render();