const standings = [
  {team:'Hyundai Unicorns', g:0, w:0, l:0},
  {team:'Samsung Lions', g:0, w:0, l:0},
  {team:'KT wiz', g:0, w:0, l:0},
  {team:'Yakult Swallows', g:0, w:0, l:0}
];
const games = [
  {round:1,home:'Samsung Lions',away:'KT wiz'},{round:1,home:'Yakult Swallows',away:'Hyundai Unicorns'},{round:2,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:2,home:'KT wiz',away:'Yakult Swallows'},
  {round:3,home:'KT wiz',away:'Hyundai Unicorns'},{round:3,home:'Yakult Swallows',away:'Samsung Lions'},{round:4,home:'KT wiz',away:'Samsung Lions'},{round:4,home:'Hyundai Unicorns',away:'Yakult Swallows'},
  {round:5,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:5,home:'Yakult Swallows',away:'KT wiz'},{round:6,home:'Hyundai Unicorns',away:'KT wiz'},{round:6,home:'Samsung Lions',away:'Yakult Swallows'},
  {round:7,home:'KT wiz',away:'Samsung Lions'},{round:7,home:'Hyundai Unicorns',away:'Yakult Swallows'},{round:8,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:8,home:'Yakult Swallows',away:'KT wiz'},
  {round:9,home:'Hyundai Unicorns',away:'KT wiz'},{round:9,home:'Samsung Lions',away:'Yakult Swallows'},{round:10,home:'Samsung Lions',away:'KT wiz'},{round:10,home:'Yakult Swallows',away:'Hyundai Unicorns'},
  {round:11,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:11,home:'KT wiz',away:'Yakult Swallows'},{round:12,home:'KT wiz',away:'Hyundai Unicorns'},{round:12,home:'Yakult Swallows',away:'Samsung Lions'},
  {round:13,home:'KT wiz',away:'Samsung Lions'},{round:13,home:'Hyundai Unicorns',away:'Yakult Swallows'},{round:14,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:14,home:'Yakult Swallows',away:'KT wiz'},
  {round:15,home:'Hyundai Unicorns',away:'KT wiz'},{round:15,home:'Samsung Lions',away:'Yakult Swallows'},{round:16,home:'Samsung Lions',away:'KT wiz'},{round:16,home:'Yakult Swallows',away:'Hyundai Unicorns'},
  {round:17,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:17,home:'KT wiz',away:'Yakult Swallows'},{round:18,home:'KT wiz',away:'Hyundai Unicorns'},{round:18,home:'Yakult Swallows',away:'Samsung Lions'},
  {round:19,home:'Samsung Lions',away:'KT wiz'},{round:19,home:'Yakult Swallows',away:'Hyundai Unicorns'},{round:20,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:20,home:'KT wiz',away:'Yakult Swallows'},
  {round:21,home:'KT wiz',away:'Hyundai Unicorns'},{round:21,home:'Yakult Swallows',away:'Samsung Lions'},{round:22,home:'KT wiz',away:'Samsung Lions'},{round:22,home:'Hyundai Unicorns',away:'Yakult Swallows'},
  {round:23,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:23,home:'Yakult Swallows',away:'KT wiz'},{round:24,home:'Hyundai Unicorns',away:'KT wiz'},{round:24,home:'Samsung Lions',away:'Yakult Swallows'}
];
const teams=[{name:'Hyundai Unicorns',city:'HCBB',logo:'hyundai'},{name:'KT wiz',city:'HCBB',logo:'kt'},{name:'Samsung Lions',city:'HCBB',logo:'samsung'},{name:'Yakult Swallows',city:'HCBB',logo:'yakult'}];
const rosters={};
function renderStandings(){const body=document.querySelector('#standings-body');if(!body)return;body.innerHTML=standings.map((x,i)=>{const pct=x.g?(x.w/x.g).toFixed(3).replace('0',''):'-';return `<tr><td class="rank">${i+1}</td><td class="team-name">${x.team}</td><td>${x.g}</td><td>${x.w}</td><td>${x.l}</td><td>${pct}</td></tr>`}).join('')}
function getKoreaDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function renderSchedule(){const list=document.querySelector('#schedule-list');if(!list)return;const today=getKoreaDate();const notices=Array.isArray(window.kfbScheduleNotices)?window.kfbScheduleNotices.filter(n=>n.date===today).sort((a,b)=>(a.time||'').localeCompare(b.time||'')):[];if(notices.length){list.innerHTML=`<div class="schedule-round"><h3>오늘의 경기 · ${today}</h3>${notices.map(n=>`<article class="match"><div class="match-teams"><span>${n.match||'경기'}</span></div><div class="match-status">${n.time||'경기 예정'}</div><p class="schedule-notice">${n.content||''}</p></article>`).join('')}</div>`}else{list.innerHTML=`<div class="schedule-round"><h3>오늘의 경기 · ${today}</h3><div class="match"><div class="match-teams"><span>오늘 등록된 경기 공지가 없습니다.</span></div><div class="match-status">NO NOTICE</div></div></div>`}}
function renderTeams(){const root=document.querySelector('#teams-grid');if(!root)return;root.innerHTML=teams.map(t=>{const logo=t.logo==='yakult'?`<img class="team-logo-img" src="https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Yakult%20Swallows%20insignia.svg" alt="${t.name} logo">`:`<div class="team-logo team-logo-${t.logo}" aria-label="${t.name} logo"></div>`;return `<article class="team-card">${logo}<h3>${t.name}</h3><p>${t.city}</p></article>`}).join('')}
function renderRosters(){const root=document.querySelector('#rosters-grid');if(!root)return;root.innerHTML='<p>Roster data loaded from KFB League roster records.</p>'}
function fmt(n){return Number(n||0).toLocaleString('en-US')}
function rate(n,d){return d?Number(n/d).toFixed(3).replace(/^0/,''):'.000'}
function playerStatsCard(nick,s){const ab=Number(s.ab)||0,h=Number(s.h)||0,d=Number(s.doubles)||0,t=Number(s.triples)||0,hr=Number(s.hr)||0,bb=Number(s.bb)||0;return `<article class="player-card"><div class="player-card-top"><div><p class="eyebrow">PLAYER PROFILE</p><h3>${nick}</h3><small>${s.team||'KFB League'}</small></div><span class="player-badge">2026 SEASON</span></div><div class="player-stat-highlight"><div><strong>${s.batting_avg!=null?Number(s.batting_avg).toFixed(3):rate(h,ab)}</strong><span>AVG</span></div><div><strong>${fmt(h)}</strong><span>HITS</span></div><div><strong>${fmt(hr)}</strong><span>HOME RUNS</span></div><div><strong>${fmt(s.rbi)}</strong><span>RBI</span></div></div><div class="player-stat-grid"><span>GP <b>${fmt(s.gp)}</b></span><span>H <b>${fmt(h)}</b></span><span>HR <b>${fmt(hr)}</b></span><span>RBI <b>${fmt(s.rbi)}</b></span><span>SB <b>${fmt(s.stolen_bases)}</b></span><span>W <b>${fmt(s.wins)}</b></span><span>ERA <b>${s.era!=null?Number(s.era).toFixed(2):'0.00'}</b></span><span>2B <b>${fmt(d)}</b></span><span>3B <b>${fmt(t)}</b></span><span>BB <b>${fmt(bb)}</b></span></div></article>`}
function renderPlayers(query=''){const root=document.querySelector('#player-results');if(!root)return;const combined={...(window.kfbDbPlayers||{}),...(playerStats||{})};const q=query.trim().toLowerCase();const entries=Object.entries(combined);if(!q){root.innerHTML=`<div class="player-empty"><strong>Search for a player nickname</strong><span>Try: mico24524, xck018, BaIemoon...</span></div>`;return}const matches=entries.filter(([nick,s])=>nick.toLowerCase().includes(q)||(s.team||'').toLowerCase().includes(q));if(!matches.length){root.innerHTML=`<div class="player-empty"><strong>No player found</strong><span>Check the nickname and try again.</span></div>`;return}root.innerHTML=matches.slice(0,20).map(([n,s])=>playerStatsCard(n,s)).join('')}
function initPlayerSearch(){const input=document.querySelector('#player-search-input');const clear=document.querySelector('#player-search-clear');if(!input)return;input.addEventListener('input',e=>renderPlayers(e.target.value));clear.addEventListener('click',()=>{input.value='';renderPlayers('');input.focus()});renderPlayers('')}
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');if(toggle){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
document.querySelector('#year').textContent=new Date().getFullYear();
renderStandings();renderSchedule();renderTeams();renderRosters();initPlayerSearch();
