const standings = [
  {team:'Hyundai Unicorns', g:0, w:0, l:0},
  {team:'Samsung Lions', g:0, w:0, l:0},
  {team:'KT wiz', g:0, w:0, l:0},
  {team:'Yakult Swallows', g:0, w:0, l:0}
];
const games = [
  {round:1,home:'Samsung Lions',away:'KT wiz'},{round:1,home:'Yakult Swallows',away:'Hyundai Unicorns'},{round:2,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:2,home:'KT wiz',away:'Yakult Swallows'},
  {round:3,home:'KT wiz',away:'Hyundai Unicorns'},{round:3,home:'Yakult Swallows',away:'Samsung Lions'},{round:4,home:'KT wiz',away:'Samsung Lions'},{round:4,home:'Hyundai Unicorns',away:'Yakult Swallows'},
  {round:5,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:5,home:'Yakult Swallows',away:'KT wiz'},{round:6,home:'Hyundai Unicorns',away:'KT wiz'},{round:6,home:'Samsung Lions',away:'Yakult Swallows'},
  {round:7,home:'KT wiz',away:'Samsung Lions'},{round:7,home:'Hyundai Unicorns',away:'Yakult Swallows'},{round:8,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:8,home:'Yakult Swallows',away:'KT wiz'},
  {round:9,home:'Hyundai Unicorns',away:'KT wiz'},{round:9,home:'Samsung Lions',away:'Yakult Swallows'},{round:10,home:'Samsung Lions',away:'KT wiz'},{round:10,home:'Yakult Swallows',away:'Hyundai Unicorns'},
  {round:11,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:11,home:'KT wiz',away:'Yakult Swallows'},{round:12,home:'KT wiz',away:'Hyundai Unicorns'},{round:12,home:'Yakult Swallows',away:'Samsung Lions'},
  {round:13,home:'KT wiz',away:'Samsung Lions'},{round:13,home:'Hyundai Unicorns',away:'Yakult Swallows'},{round:14,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:14,home:'Yakult Swallows',away:'KT wiz'},
  {round:15,home:'Hyundai Unicorns',away:'KT wiz'},{round:15,home:'Samsung Lions',away:'Yakult Swallows'},{round:16,home:'Samsung Lions',away:'KT wiz'},{round:16,home:'Yakult Swallows',away:'Hyundai Unicorns'},
  {round:17,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:17,home:'KT wiz',away:'Yakult Swallows'},{round:18,home:'KT wiz',away:'Hyundai Unicorns'},{round:18,home:'Yakult Swallows',away:'Samsung Lions'},
  {round:19,home:'Samsung Lions',away:'KT wiz'},{round:19,home:'Yakult Swallows',away:'Hyundai Unicorns'},{round:20,home:'Hyundai Unicorns',away:'Samsung Lions'},{round:20,home:'KT wiz',away:'Yakult Swallows'},
  {round:21,home:'KT wiz',away:'Hyundai Unicorns'},{round:21,home:'Yakult Swallows',away:'Samsung Lions'},{round:22,home:'KT wiz',away:'Samsung Lions'},{round:22,home:'Hyundai Unicorns',away:'Yakult Swallows'},
  {round:23,home:'Samsung Lions',away:'Hyundai Unicorns'},{round:23,home:'Yakult Swallows',away:'KT wiz'},{round:24,home:'Hyundai Unicorns',away:'KT wiz'},{round:24,home:'Samsung Lions',away:'Yakult Swallows'}
];
const teams=[{name:'Hyundai Unicorns',city:'HCBB',logo:'hyundai'},{name:'KT wiz',city:'HCBB',logo:'kt'},{name:'Samsung Lions',city:'HCBB',logo:'samsung'},{name:'Yakult Swallows',city:'HCBB',logo:'yakult'}];
const rosters={
'Yakult Swallows':{staff:[['Pre-sign','blaxkstra_a',''],['AM','1Lov3_Darin',''],['AM','DANA_X1126',''],['AM','blaxkstra_a','']],players:[['1','xck018','19+'],['2','VorZaves','13~18'],['3','owldoskq','19+'],['4','kosame55','7~12'],['5','1Lov3_HW','7~12'],['6','woozlordd','13~18'],['7','1Lov3_Doy0un9','7~12'],['8','ANYWAY789','13~18'],['9','hamzziii','19+'],['10','ggkkbt21','7~12'],['11','Akon_Kon','13~18'],['12','1Lov3_Darin',''],['13','DANA_X1126','13~18'],['14','ShaltNK',''],['15','dddfdsfc',''],['16','Cola_1034657',''],['17','willie06080',''],['18','youdam2001',''],['19','0X_Perfect',''],['20','ghffhthhf',''],['21','qwweush',''],['22','tsnsjjssjjd',''],['23','gorsky7',''],['24','',''],['25','',''],['26','',''],['27','',''],['28','',''],['29','',''],['30','']]},
'KT wiz':{staff:[['Pre-sign','Jeongliarz',''],['AM','Jeongliarz',''],['AM','BaIemoon',''],['AM','YutaNalDo','']],players:[['1','BaIemoon','13~18'],['2','Rozu_1x',''],['3','Gre4n_Love','19+'],['4','CUTI_STREET','19+'],['5','jongpyokurai','19+'],['6','terry0185','7~12'],['7','rayray24257978','7~12'],['8','kyota_kana','7~12'],['9','',''],['10','ncd1nos','13~18'],['11','KOREA_goodgubber','19+'],['12','JerryEEENTNL','7~12'],['13','Sam0705_Sam0705',''],['14','YutaNalDo',''],['15','heerak2',''],['16','sy_adi',''],['17','ddnwwagefd9991',''],['18','yu_x0412',''],['19','sa1vationtrinity',''],['20','kiabojiz',''],['21','imgodkaito',''],['22','H1n_Lx5h',''],['23','Insanetricx',''],['24','EIL1sback',''],['25','',''],['26','',''],['27','',''],['28','',''],['29','',''],['30','']]},
'Hyundai Unicorns':{staff:[['Pre-sign','ShiroaDoll',''],['AM','ShiroaDoll',''],['AM','nicemanman_1',''],['AM','wakashizz','']],players:[['1','ho_0xz','13~18'],['2','wakashizz','13~18'],['3','nicemanman_1','19+'],['4','xxsks_ekw','19+'],['5','mandoo_19','7~12'],['6','klk122380','19+'],['7','X_csm','13~18'],['8','ksmzsm123','13~18'],['9','Mylovesk62','19+'],['10','apexghte','19+'],['11','RxitoVII','19+'],['12','Q_LDL','7~12'],['13','hwgahw76',''],['14','graa_nice',''],['15','Yoongichan0902',''],['16','djhxjffj0',''],['17','STINSONA',''],['18','npm_apple',''],['19','KRsungjae',''],['20','JS13416',''],['21','KimDoYoung_Good',''],['22','Sam0705_Sam0705',''],['23','kingkueen0s',''],['24','OREO_5744',''],['25','1ee_youngchan',''],['26','needam0721',''],['27','splint111',''],['28','1Lov3_donghee',''],['29','',''],['30','']]},
'Samsung Lions':{staff:[['Pre-sign','mico24524',''],['AM','mico24524',''],['AM','Ak1Kurai',''],['AM','NOOB_dghm','']],players:[['1','Ak1Kurai','13~18'],['2','NOOB_dghm','13~18'],['3','imnotswomi3','13~18'],['4','cool327000','7~12'],['5','kgimpepepspepe','19+'],['6','AdenElec','7~12'],['7','FINX_Z7','7~12'],['8','TheYoungKing_N05','13~18'],['9','GAEQ_74HRUE','7~12'],['10','koreahom123467','19+'],['11','sdy131221','19+'],['12','dex1va1ly','1~6'],['13','crvhjc',''],['14','EZEZEZoqo',''],['15','Kevin707952',''],['16','ezgame0303',''],['17','demon_091033',''],['18','Acthdfgvj',''],['19','12twelve25',''],['20','chosankru39',''],['21','WgoodS1un_n1cegoodz',''],['22','s9sdsei',''],['23','kaname030844',''],['24','aofo5934',''],['25','tttttttrrrtttttttt',''],['26','qqedcjdxcg',''],['27','woojin_0503',''],['28','10wjwdgha',''],['29','dgshjgdj',''],['30','SHJBMV','']]}
};
function renderStandings(){const body=document.querySelector('#standings-body');if(!body)return;body.innerHTML=standings.map((x,i)=>{const pct=x.g?(x.w/x.g).toFixed(3).replace('0',''):'-';return `<tr><td class="rank">${i+1}</td><td class="team-name">${x.team}</td><td>${x.g}</td><td>${x.w}</td><td>${x.l}</td><td>${pct}</td></tr>`}).join('')}
function renderSchedule(){const list=document.querySelector('#schedule-list');if(!list)return;const rounds=[...new Set(games.map(g=>g.round))];list.innerHTML=rounds.map(round=>`<div class="schedule-round"><h3>Round ${round}</h3>${games.filter(g=>g.round===round).map(g=>`<article class="match"><div class="match-teams"><span>${g.away}</span><span class="vs">@</span><span>${g.home}</span></div><div class="match-status">Scheduled</div></article>`).join('')}</div>`).join('')}
function renderTeams(){const root=document.querySelector('#teams-grid');if(!root)return;root.innerHTML=teams.map(t=>{const logo=t.logo==='yakult'?`<img class="team-logo-img" src="https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Yakult%20Swallows%20insignia.svg" alt="${t.name} logo">`:`<div class="team-logo team-logo-${t.logo}" aria-label="${t.name} logo"></div>`;return `<article class="team-card">${logo}<h3>${t.name}</h3><p>${t.city}</p></article>`}).join('')}
function renderRosters(){const root=document.querySelector('#rosters-grid');if(!root)return;root.innerHTML=Object.entries(rosters).map(([team,data])=>`<article class="roster-card"><div class="roster-card-head"><div><p class="eyebrow">ROSTER</p><h3>${team}</h3></div><span>30 slots</span></div><div class="roster-staff">${data.staff.map(s=>`<div class="roster-row staff-row"><span>${s[0]}</span><strong>${s[1]}</strong><em>${s[2]}</em></div>`).join('')}</div><div class="roster-table-wrap"><table class="roster-table"><thead><tr><th>#</th><th>Player</th><th>Age Group</th></tr></thead><tbody>${data.players.map(p=>`<tr><td>${p[0]||'—'}</td><td>${p[1]||'—'}</td><td>${p[2]||'—'}</td></tr>`).join('')}</tbody></table></div></article>`).join('')}
function fmt(n){return Number(n||0).toLocaleString('en-US')}
function rate(n,d){return d?Number(n/d).toFixed(3).replace(/^0/,''):'.000'}
function playerStatsCard(nick,s){const ab=Number(s.ab)||0,h=Number(s.h)||0,d=Number(s.doubles)||0,t=Number(s.triples)||0,hr=Number(s.hr)||0,bb=Number(s.bb)||0;const tb=(h-d-t-hr)+2*d+3*t+4*hr;const obp=(h+bb)/(ab+bb);const slg=tb/ab;return `<article class="player-card"><div class="player-card-top"><div><p class="eyebrow">PLAYER PROFILE</p><h3>${nick}</h3><small>${s.team||'KFB League'}</small></div><span class="player-badge">2026 SEASON</span></div><div class="player-stat-highlight"><div><strong>${rate(h,ab)}</strong><span>AVG</span></div><div><strong>${fmt(h)}</strong><span>HITS</span></div><div><strong>${fmt(hr)}</strong><span>HOME RUNS</span></div><div><strong>${fmt(s.rbi)}</strong><span>RBI</span></div></div><div class="player-stat-grid"><span>GP <b>${fmt(s.gp)}</b></span><span>PA <b>${fmt(s.pa)}</b></span><span>AB <b>${fmt(ab)}</b></span><span>2B <b>${fmt(d)}</b></span><span>3B <b>${fmt(t)}</b></span><span>BB <b>${fmt(bb)}</b></span><span>SO <b>${fmt(s.so)}</b></span><span>OBP <b>${rate(h+bb,ab+bb)}</b></span><span>SLG <b>${rate(tb,ab)}</b></span><span>TB <b>${fmt(tb)}</b></span></div></article>`}
function renderPlayers(query=''){const root=document.querySelector('#player-results');if(!root)return;const q=query.trim().toLowerCase();const entries=Object.entries(playerStats||{});if(!q){root.innerHTML=`<div class="player-empty"><strong>Search for a player nickname</strong><span>Try: xck018, VorZaves, BaIemoon...</span></div>`;return}const matches=entries.filter(([nick,s])=>nick.toLowerCase().includes(q)||(s.team||'').toLowerCase().includes(q));if(!matches.length){root.innerHTML=`<div class="player-empty"><strong>No player found</strong><span>Check the nickname and try again.</span></div>`;return}root.innerHTML=matches.slice(0,20).map(([n,s])=>playerStatsCard(n,s)).join('')}
function initPlayerSearch(){const input=document.querySelector('#player-search-input');const clear=document.querySelector('#player-search-clear');if(!input)return;input.addEventListener('input',e=>renderPlayers(e.target.value));clear.addEventListener('click',()=>{input.value='';renderPlayers('');input.focus()});renderPlayers('')}
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');if(toggle){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
document.querySelector('#year').textContent=new Date().getFullYear();
renderStandings();renderSchedule();renderTeams();renderRosters();initPlayerSearch();