const standings = [
  {team:'Hyundai Unicorns', g:0, w:0, l:0},
  {team:'Samsung Lions', g:0, w:0, l:0},
  {team:'KT wiz', g:0, w:0, l:0},
  {team:'Yakult Swallows', g:0, w:0, l:0}
];
const teams=[{name:'Hyundai Unicorns',city:'HCBB',logo:'hyundai'},{name:'KT wiz',city:'HCBB',logo:'kt'},{name:'Samsung Lions',city:'HCBB',logo:'samsung'},{name:'Yakult Swallows',city:'HCBB',logo:'yakult'}];
const rosters={};
function renderStandings(){const body=document.querySelector('#standings-body');if(!body)return;body.innerHTML=standings.map((x,i)=>{const pct=x.g?(x.w/x.g).toFixed(3).replace('0',''):'-';return `<tr><td class="rank">${i+1}</td><td class="team-name">${x.team}</td><td>${x.g}</td><td>${x.w}</td><td>${x.l}</td><td>${pct}</td></tr>`}).join('')}
function renderTeams(){const root=document.querySelector('#teams-grid');if(!root)return;root.innerHTML=teams.map(t=>{const logo=t.logo==='yakult'?`<img class="team-logo-img" src="https://commons.wikimedia.org/wiki/Special:FilePath/Tokyo%20Yakult%20Swallows%20insignia.svg" alt="${t.name} logo">`:`<div class="team-logo team-logo-${t.logo}" aria-label="${t.name} logo"></div>`;return `<article class="team-card">${logo}<h3>${t.name}</h3><p>${t.city}</p></article>`}).join('')}
function renderRosters(){const root=document.querySelector('#rosters-grid');if(!root)return;root.innerHTML='<p>Roster data loaded from KFB League roster records.</p>'}
function fmt(n){return Number(n||0).toLocaleString('en-US')}
function rate(n,d){return d?Number(n/d).toFixed(3).replace(/^0/,''):'.000'}
function playerStatsCard(nick,s){const ab=Number(s.ab)||0,h=Number(s.h)||0,d=Number(s.doubles)||0,t=Number(s.triples)||0,hr=Number(s.hr)||0,bb=Number(s.bb)||0;return `<article class="player-card"><div class="player-card-top"><div><p class="eyebrow">PLAYER PROFILE</p><h3>${nick}</h3><small>${s.team||'KFB League'}</small></div><span class="player-badge">2026 SEASON</span></div><div class="player-stat-highlight"><div><strong>${s.batting_avg!=null?Number(s.batting_avg).toFixed(3):rate(h,ab)}</strong><span>AVG</span></div><div><strong>${fmt(h)}</strong><span>HITS</span></div><div><strong>${fmt(hr)}</strong><span>HOME RUNS</span></div><div><strong>${fmt(s.rbi)}</strong><span>RBI</span></div></div><div class="player-stat-grid"><span>GP <b>${fmt(s.gp)}</b></span><span>H <b>${fmt(h)}</b></span><span>HR <b>${fmt(hr)}</b></span><span>RBI <b>${fmt(s.rbi)}</b></span><span>SB <b>${fmt(s.stolen_bases)}</b></span><span>W <b>${fmt(s.wins)}</b></span><span>ERA <b>${s.era!=null?Number(s.era).toFixed(2):'0.00'}</b></span><span>2B <b>${fmt(d)}</b></span><span>3B <b>${fmt(t)}</b></span><span>BB <b>${fmt(bb)}</b></span></div></article>`}
function renderPlayers(query=''){const root=document.querySelector('#player-results');if(!root)return;const combined={...(window.kfbDbPlayers||{}),...(playerStats||{})};const q=query.trim().toLowerCase();const entries=Object.entries(combined);if(!q){root.innerHTML=`<div class="player-empty"><strong>Search for a player nickname</strong><span>Try: mico24524, xck018, BaIemoon...</span></div>`;return}const matches=entries.filter(([nick,s])=>nick.toLowerCase().includes(q)||(s.team||'').toLowerCase().includes(q));if(!matches.length){root.innerHTML=`<div class="player-empty"><strong>No player found</strong><span>Check the nickname and try again.</span></div>`;return}root.innerHTML=matches.slice(0,20).map(([n,s])=>playerStatsCard(n,s)).join('')}
function initPlayerSearch(){const input=document.querySelector('#player-search-input');const clear=document.querySelector('#player-search-clear');if(!input)return;input.addEventListener('input',e=>renderPlayers(e.target.value));clear.addEventListener('click',()=>{input.value='';renderPlayers('');input.focus()});renderPlayers('')}
function renderLeaderList(id,rows,format){const root=document.querySelector(id);if(!root)return;root.innerHTML=rows.length?rows.map((p,i)=>`<div class="leader-row"><span class="leader-rank">${i+1}</span><div class="leader-player"><strong>${p.nick}</strong><small>${p.team||'KFB League'}</small></div><b class="leader-value">${format(p)}</b></div>`).join(''):'<div class="leader-empty">No records yet.</div>'}
function renderRecords(){const source=Object.entries(playerStats||{}).map(([nick,s])=>({nick,s,team:s.team||'KFB League',hr:Number(s.hr)||0,ab:Number(s.ab)||0,h:Number(s.h)||0,era:Number(s.era)||0,pa:Number(s.pa)||0}));const hr=source.slice().sort((a,b)=>b.hr-a.hr||b.h-a.h).slice(0,10);const avg=source.slice().sort((a,b)=>{const aAvg=a.ab>0?a.h/a.ab:0;const bAvg=b.ab>0?b.h/b.ab:0;return bAvg-aAvg||b.pa-a.pa||b.ab-a.ab||b.h-a.h}).slice(0,10);const era=source.filter(p=>p.era!==0).slice().sort((a,b)=>a.era-b.era).slice(0,10);renderLeaderList('#home-run-leaders',hr,p=>fmt(p.hr));renderLeaderList('#batting-average-leaders',avg,p=>(p.ab>0?p.h/p.ab:0).toFixed(3).replace(/^0/,''));renderLeaderList('#era-leaders',era,p=>p.era.toFixed(2))}
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');if(toggle){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
document.querySelector('#year').textContent=new Date().getFullYear();
renderStandings();renderTeams();renderRosters();initPlayerSearch();renderRecords();
